# This rule is not used by the project kube-operator2dir itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ops.operator2dir resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-operator2dir
    app.kubernetes.io/managed-by: kustomize
  name: dirtree-viewer-role
rules:
- apiGroups:
  - ops.operator2dir
  resources:
  - dirtrees
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.operator2dir
  resources:
  - dirtrees/status
  verbs:
  - get
